# MACE Optimization Parameters
# 이 파일을 복사하여 시스템별로 수정

optimizer: BFGS # BFGS | FIRE | LBFGS
fmax: 0.05 # 수렴 기준 (eV/Å)
max_steps: 200 # 최대 반복


# PBC 설정 (pipeline_config.yaml의 cell에서 자동 상속됨)
# 직접 지정하려면 아래 주석 해제
# pbc:
#   - [15.0, 0.0, 0.0]
#   - [0.0, 15.0, 0.0]
#   - [0.0, 0.0, 25.0]
